# =====================================================
# QERRA-v2 Classical Edition — Main API
# Version: 2.0.0 (Hardened & Watchdog-Protected)
# Three-layer architecture:
#   Layer 2 — QERRA-HSR v0.1 (physical safety, pure Python)
#   Layer 1 — SEMEV-12 v1.9.0 (moral deliberation, semantic batch)
#   Layer 3 — QERRA-THRIVE v2.0.0 (values companion, action ranker)
#
# Unified Pipeline (Filter-First Architecture with 800ms Fail-Closed Watchdog):
#   1. Layer 2 HSR: Reflexive safety check.
#   2. Layer 1 SEMEV-12: Filters out morally hazardous candidates in 1 neural batch pass.
#   3. Layer 3 THRIVE: Ranks only the surviving safe candidates.
# =====================================================

import asyncio
from typing import Optional, List, Dict, Any
from dotenv import load_dotenv
from fastapi import FastAPI, Depends, Request, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field, field_validator
from slowapi import Limiter
from slowapi.util import get_remote_address

from classical_analyze import analyze_text, analyze_text_batch
from vectors import get_semev12_vectors
from utils.response import api_response
from auth.api_key import require_api_key

# Layer 2: QERRA-HSR
from hsr.qerra_hsr import evaluate_hsr, HSRInput, HSRStatus

# Layer 3: QERRA-THRIVE Package
import values

load_dotenv()

limiter = Limiter(key_func=get_remote_address)

app = FastAPI(
    title="QERRA-v2 Classical",
    description="Three-layer ethical, physical, and value-based safety middleware for robotics.",
    version="2.0.0"
)

app.state.limiter = limiter

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

# 800ms ROS 2 Real-Time Fail-Closed Watchdog Budget
WATCHDOG_TIMEOUT_SECONDS = 0.800


# =====================================================
# Request Models
# =====================================================

class HSRSignals(BaseModel):
    distress_confidence: float       # 0.0–1.0 from robot perception stack
    persons_nearby_count: int        # upright, responsive humans nearby
    hazard_proximity_flag: bool      # confirmed hazard near a human
    robot_task_interruptible: bool   # affects HOW, never WHETHER


class CombinedRequest(BaseModel):
    """Input model for two-layer evaluation (Layers 1 & 2)."""
    text: str = Field(
        ...,
        min_length=10,
        max_length=5000,
        description="The situation to evaluate (10–5000 characters)"
    )
    hsr_signals: Optional[HSRSignals] = None

    @field_validator("text")
    @classmethod
    def text_must_not_be_empty(cls, v):
        if not v.strip():
            raise ValueError("Text cannot be empty or only whitespace")
        return v.strip()


class RankRequest(BaseModel):
    """Input model for Layer 3 standalone action ranking."""
    vector_name: str = Field(
        ...,
        description="The Layer 3 THRIVE vector to evaluate"
    )
    candidates: List[str] = Field(
        ...,
        min_items=2,
        max_items=10,
        description="List of 2 to 10 candidate action text strings to rank"
    )


class PipelineRequest(BaseModel):
    """Input model for the Unified 3-Layer Evaluation Pipeline."""
    task_context: str = Field(
        ...,
        min_length=5,
        max_length=5000,
        description="High-level description of the task or situation"
    )
    vector_name: str = Field(
        ...,
        description="The Layer 3 THRIVE vector to rank candidate actions"
    )
    candidates: List[str] = Field(
        ...,
        min_items=2,
        max_items=10,
        description="Candidate action choices generated by the robot planner"
    )
    hsr_signals: Optional[HSRSignals] = None


# =====================================================
# Helper: Strict Vector Whitelist Validator
# =====================================================

def get_validated_ranker(vector_name: str):
    """Validates vector_name against ALL_THRIVE_VECTORS and resolves ranking function."""
    clean_name = vector_name[5:] if vector_name.startswith("rank_") else vector_name
    if clean_name not in values.ALL_THRIVE_VECTORS:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown Layer 3 vector '{vector_name}'. Allowed: {values.ALL_THRIVE_VECTORS}"
        )
    func_name = f"rank_{clean_name}"
    ranker_func = getattr(values, func_name, None)
    if ranker_func is None:
        raise HTTPException(status_code=500, detail=f"Ranking function '{func_name}' not resolved.")
    return ranker_func


# =====================================================
# Main Endpoint — /analyze (Layers 1 & 2 Gating)
# =====================================================

@app.post("/analyze", dependencies=[Depends(require_api_key)])
@limiter.limit("20/minute")
def analyze(request: Request, data: CombinedRequest):
    """Two-layer ethical and physical safety evaluation (SEMEV-12 + QERRA-HSR)."""
    hsr_result_payload = None
    semev12_suspended = False

    if data.hsr_signals is not None:
        hsr_input = HSRInput(
            distress_confidence=data.hsr_signals.distress_confidence,
            persons_nearby_count=data.hsr_signals.persons_nearby_count,
            hazard_proximity_flag=data.hsr_signals.hazard_proximity_flag,
            robot_task_interruptible=data.hsr_signals.robot_task_interruptible,
        )

        hsr_result = evaluate_hsr(hsr_input)
        hsr_result_payload = {
            "status": hsr_result.status.value,
            "vectors_activated": hsr_result.vectors_activated,
            "reasoning": hsr_result.reasoning,
            "version": hsr_result.version,
        }

        if hsr_result.status == HSRStatus.CRITICAL:
            semev12_suspended = True
            return api_response({
                "hsr": hsr_result_payload,
                "semev12_suspended": semev12_suspended,
                "suspended_instruction": data.text,
                "data": {},
                "note": "QERRA-HSR returned CRITICAL. SEMEV-12 ethical evaluation suspended."
            })

    semev12_result = analyze_text(data.text)

    return api_response({
        "hsr": hsr_result_payload,
        "semev12_suspended": semev12_suspended,
        "data": semev12_result,
    })


# =====================================================
# Layer 3 Standalone Endpoint — /rank (Action Ranker)
# =====================================================

@app.post("/rank", dependencies=[Depends(require_api_key)])
@limiter.limit("20/minute")
def rank_actions(request: Request, data: RankRequest):
    """Layer 3 standalone action ranking across candidate texts with whitelist guard."""
    ranker_func = get_validated_ranker(data.vector_name)

    try:
        result = ranker_func(data.candidates)
        return api_response({
            "framework": "QERRA-THRIVE Layer 3",
            "version": "2.0.0",
            "advisory_only": True,
            "result": result
        })
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Layer 3 execution error on vector '{data.vector_name}': {str(e)}"
        )


# =====================================================
# UNIFIED 3-LAYER PIPELINE CORE EXECUTION
# =====================================================

def _execute_pipeline_core(data: PipelineRequest) -> dict:
    """Synchronous core evaluation execution."""
    # ── 1. LAYER 2: QERRA-HSR Physical Safety Reflex Check ───────────
    hsr_payload = None
    if data.hsr_signals is not None:
        hsr_input = HSRInput(
            distress_confidence=data.hsr_signals.distress_confidence,
            persons_nearby_count=data.hsr_signals.persons_nearby_count,
            hazard_proximity_flag=data.hsr_signals.hazard_proximity_flag,
            robot_task_interruptible=data.hsr_signals.robot_task_interruptible,
        )
        hsr_res = evaluate_hsr(hsr_input)
        hsr_payload = {
            "status": hsr_res.status.value,
            "vectors_activated": hsr_res.vectors_activated,
            "reasoning": hsr_res.reasoning,
        }

        # If Physical Safety is CRITICAL, abort pipeline immediately
        if hsr_res.status == HSRStatus.CRITICAL:
            return {
                "pipeline_status": "ABORTED_PHYSICAL_SAFETY",
                "recommendation": "halt_safety_response",
                "chosen_action": None,
                "layer_2_hsr": hsr_payload,
                "layer_1_filtered_candidates": [],
                "layer_3_thrive": None,
                "note": "QERRA-HSR returned CRITICAL. Higher-layer deliberation suspended."
            }

    # ── 2. LAYER 1: SEMEV-12 Moral Safety Filtering (Batch) ───────────
    semev_batch_results = analyze_text_batch(data.candidates)

    safe_survivors: List[str] = []
    blocked_candidates: List[Dict[str, Any]] = []

    for text, semev_res in zip(data.candidates, semev_batch_results):
        decision = semev_res.get("decision", "modified")
        if decision == "safe":
            safe_survivors.append(text)
        else:
            blocked_candidates.append({
                "candidate": text,
                "score": semev_res.get("score"),
                "vectors_activated": semev_res.get("vectors_activated", []),
                "reasoning": semev_res.get("reasoning", ""),
            })

    # If NO candidates survive moral filtering, abort to human operator
    if not safe_survivors:
        return {
            "pipeline_status": "BLOCKED_ALL_CANDIDATES_MORAL_RISK",
            "recommendation": "ask_human",
            "chosen_action": None,
            "layer_2_hsr": hsr_payload or {"status": "NOT_EVALUATED"},
            "layer_1_blocked_candidates": blocked_candidates,
            "layer_3_thrive": None,
            "note": "All candidate actions violated SEMEV-12 moral/harm constraints. Action blocked."
        }

    # ── 3. LAYER 3: QERRA-THRIVE Action Ranking on Safe Survivors ─────
    ranker_func = get_validated_ranker(data.vector_name)

    try:
        thrive_res = ranker_func(safe_survivors)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Layer 3 ranking error on survivors: {str(e)}")

    winning_action = thrive_res.get("winner")
    thrive_fires = thrive_res.get("fires", True)

    # ── 4. Unified Synthesis & Final Decision ───────────────────────
    if not thrive_fires:
        pipeline_status = "ABSTAINED_LOW_VALUE"
        recommendation = "ask_human"
    else:
        pipeline_status = "APPROVED"
        recommendation = "choose"

    return {
        "pipeline_status": pipeline_status,
        "recommendation": recommendation,
        "chosen_action": winning_action if recommendation == "choose" else None,
        "layer_2_hsr": hsr_payload or {"status": "NOT_EVALUATED"},
        "layer_1_moral_filter": {
            "total_candidates": len(data.candidates),
            "survivors_count": len(safe_survivors),
            "blocked_count": len(blocked_candidates),
            "blocked_details": blocked_candidates,
        },
        "layer_3_thrive": {
            "vector": data.vector_name,
            "winner": winning_action,
            "fires": thrive_fires,
            "scores": thrive_res.get("adjusted_scores", thrive_res.get("scores", {})),
        }
    }


# =====================================================
# UNIFIED 3-LAYER PIPELINE ENDPOINT — /evaluate_pipeline
# (Protected by 800ms Fail-Closed Watchdog)
# =====================================================

@app.post("/evaluate_pipeline", dependencies=[Depends(require_api_key)])
@limiter.limit("20/minute")
async def evaluate_pipeline(request: Request, data: PipelineRequest):
    """
    Connected 3-Layer Evaluation Pipeline:
    1. Layer 2 (QERRA-HSR): Reflexive physical safety check. If CRITICAL -> halts immediately.
    2. Layer 1 (SEMEV-12 Filter): Single-pass batch evaluation on ALL candidates to filter moral risks.
    3. Layer 3 (QERRA-THRIVE Ranker): Ranks ONLY the surviving safe candidates.
    4. Watchdog: Hard 800ms timeout fails closed to halt_safety_response.
    """
    try:
        # Enforce 800ms hard safety watchdog limit
        result = await asyncio.wait_for(
            asyncio.to_thread(_execute_pipeline_core, data),
            timeout=WATCHDOG_TIMEOUT_SECONDS
        )
        return api_response(result)
    except asyncio.TimeoutError:
        return api_response({
            "pipeline_status": "ABORTED_PHYSICAL_SAFETY",
            "recommendation": "halt_safety_response",
            "chosen_action": None,
            "layer_2_hsr": {"status": "WATCHDOG_TIMEOUT_EXCEEDED", "timeout_ms": 800},
            "layer_1_moral_filter": None,
            "layer_3_thrive": None,
            "note": "Pipeline execution exceeded 800ms fail-closed budget. Emergency safety halt."
        })


# =====================================================
# Public Endpoints
# =====================================================

@app.get("/")
def home():
    return api_response({
        "status": "QERRA-v2 Classical Edition is live",
        "message": "Three-layer ethical, physical, and value-based safety middleware",
        "layers": {
            "qerra_hsr": "Layer 2 — Physical safety — v0.1 — 3 vectors pure Python",
            "semev12": "Layer 1 — Moral deliberation — v1.9.0 — 12 vectors semantic batch",
            "qerra_thrive": "Layer 3 — Value action ranker — v2.0.0 — 12 vectors hybrid"
        },
        "endpoints": {
            "/analyze": "Layers 1 & 2 Gating evaluation",
            "/rank": "Layer 3 Standalone action ranking",
            "/evaluate_pipeline": "Unified 3-Layer end-to-end evaluation pipeline (Filter-First, 800ms Watchdog)"
        }
    })


@app.get("/health")
def health():
    vectors = get_semev12_vectors()
    return api_response({
        "status": "healthy",
        "semev12_vectors_loaded": len(vectors),
        "thrive_vectors_loaded": len(values.ALL_THRIVE_VECTORS),
        "framework": "QERRA-v2 Classical Edition",
        "semev12_version": "1.9.0",
        "qerra_hsr_version": "0.1",
        "qerra_thrive_version": "2.0.0",
        "watchdog_timeout_ms": 800
    })


@app.get("/thrive/vectors")
def get_thrive_vectors():
    return api_response({
        "framework": "QERRA-THRIVE",
        "version": "2.0.0",
        "total_vectors": len(values.ALL_THRIVE_VECTORS),
        "suites": {
            "human_centered_suite_a": values.HUMAN_CENTERED_VECTORS,
            "ecological_suite_b": values.ECOLOGICAL_VECTORS,
        },
        "all_vectors": values.ALL_THRIVE_VECTORS,
    })


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
